{% set version = '1.7-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-e1071
  version: {{ version|replace("-", "_") }}

source:
  fn: e1071_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/e1071_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/e1071/e1071_{{ version }}.tar.gz
  sha256: 93699a2e16826459221cf7c9896d99e87fdc1c0e2e270bda302670760cbf643a

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-class
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-class

test:
  commands:
    - $R -e "library('e1071')"           # [not win]
    - "\"%R%\" -e \"library('e1071')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=e1071
  license: GPL-2
  summary: Functions for latent class analysis, short time Fourier transform, fuzzy clustering,
    support vector machines, shortest path computation, bagged clustering, naive Bayes
    classifier, ...
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
