{% set version = "1.7-17" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-e1071
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/e1071_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/e1071/e1071_{{ version }}.tar.gz
  sha256: 6debc371ad478c2aa6de1f6510e254e80e797de4974b855f63b35509a3c2ac87

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-proxy                    # [build_platform != target_platform]
    - r-class                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-class
    - r-proxy
  run:
    - r-base
    - r-class
    - r-proxy

test:
  commands:
    - $R -e "library('e1071')"           # [not win]
    - "\"%R%\" -e \"library('e1071')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=e1071
  license: GPL-2.0-or-later
  summary: Functions for latent class analysis, short time Fourier transform, fuzzy clustering, support vector machines, shortest path computation, bagged clustering, naive Bayes classifier, ...
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: e1071
# Version: 1.7-2
# Title: Misc Functions of the Department of Statistics, Probability Theory Group (Formerly: E1071), TU Wien
# Imports: graphics, grDevices, class, stats, methods, utils
# Suggests: cluster, mlbench, nnet, randomForest, rpart, SparseM, xtable, Matrix, MASS, slam
# Authors@R: c(person(given = "David", family = "Meyer", role = c("aut", "cre"), email = "David.Meyer@R-project.org"), person(given = "Evgenia", family = "Dimitriadou", role = c("aut","cph")), person(given = "Kurt", family = "Hornik", role = "aut"), person(given = "Andreas", family = "Weingessel", role = "aut"), person(given = "Friedrich", family = "Leisch", role = "aut"), person(given = "Chih-Chung", family = "Chang", role = c("ctb","cph"), comment = "libsvm C++-code"), person(given = "Chih-Chen", family = "Lin", role = c("ctb","cph"), comment = "libsvm C++-code"))
# Description: Functions for latent class analysis, short time Fourier transform, fuzzy clustering, support vector machines, shortest path computation, bagged clustering, naive Bayes classifier, ...
# License: GPL-2 | GPL-3
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2019-06-04 09:05:01 UTC; meyer
# Author: David Meyer [aut, cre], Evgenia Dimitriadou [aut, cph], Kurt Hornik [aut], Andreas Weingessel [aut], Friedrich Leisch [aut], Chih-Chung Chang [ctb, cph] (libsvm C++-code), Chih-Chen Lin [ctb, cph] (libsvm C++-code)
# Maintainer: David Meyer <David.Meyer@R-project.org>
# Repository: CRAN
# Date/Publication: 2019-06-05 08:20:27 UTC
