{% set version = "1.7-0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-e1071
  version: {{ version|replace("-", "_") }}

source:
  fn: e1071_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/e1071_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/e1071/e1071_{{ version }}.tar.gz
  sha256: 93699a2e16826459221cf7c9896d99e87fdc1c0e2e270bda302670760cbf643a

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-class
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-class
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('e1071')"  # [not win]
    - "\"%R%\" -e \"library('e1071')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=e1071
  license: GPL-2
  summary: |
    Functions for latent class analysis, short time Fourier transform, fuzzy clustering,
    support vector machines, shortest path computation, bagged clustering, naive Bayes
    classifier, ...
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
