appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
bot: {automerge: true}
provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: t90aEXnykicYeziFdYS4h+pN1PI1jeLiqbuqXRPK6Agk+lhmo/JL2tDPVTzEtZQMbmMvz6zckqHhS78UcOer1q3yHaU4abfBcor8zbKmg0KmrJ0ew9Wo2ku7yZKR0FqHtw/uoIfJO/v2VD26kbvWN7IMV9MRiBa8XIWakc8qAWKdrR/9UYwGGyCHE5vtYvfxXYj58FeG43IZ7Cz6I6qdYgbSGizeqkuDfEcMlnMszDpWi3EbbBUaEOGhkjrdEM2du2yR1FD5rM08x4q7LCudlglO/2M8qAJ7RUJyoun3JgReJYzSf5iXXeEF3i9XrUNrZ4/xk1FdwuRbtZJAZfSjKyIgVCZtQCczXNJTz1L+F2Jvj05e4NSvCaXHoOIaaN6AOh+JTMhMOUTDCU6DPhoImpPobgbSxipQrXx8PtCIBWIisEzFzDuVb1H/0mn8w/7/fedNfxOHYjoErhRGWxFZk61y2x4F6CIeO+zV75QEteiN/pjcy0E37F09oDE926Vk9T2/Ohzu9UxMA4woykOBm0wKDBMVx7ZKS85OeBV+rcsWqdfVe464jKc1G7hMaA5PMqBPet/Karzo3+yBSj0FYnhjvhAigE6CEX7p9ST5WV8mvKWSL286ao8afGrreu+kEZtr3BZ0u73dEk96HPiFF9Q3aD1Rznq0F45z7GFTqqg=}
conda_forge_output_validation: true
